Repository iNZightVIT/iNZight, pull requests merged in 2019-04, with the labels that each got.

#156 Feature/import sas
  .travis.yml
  NEWS.Md
  R/iNZImportWin.R
  R/iNZMenuBarWidget.R
  appveyor.yml
  tests/testthat/cars.xpt
  tests/testthat/test.sas7bdat
  tests/testthat/test_data_loads.R
Labels: bug, enhancement

#158 Hotfix/getsummary
  DESCRIPTION
  NEWS.Md
  R/iNZGUI.R
Labels: bug

#159 Hotfix/getsummary into dev
  DESCRIPTION
  NEWS.Md
  R/iNZGUI.R
Labels: bug

#162 Bugfix/import datatype
  R/iNZImportWin.R
  tests/testthat/test_data_loads.R
Labels: bug

#163 Allow date/time vartypes (in csv, for now) (#152)
  R/iNZDataViewWidget.R
  R/iNZImportWin.R
  tests/testthat/dt.csv
  tests/testthat/test_data_loads.R
Labels: enhancement

#154 Feature/dataop
  R/iNZChangeDataWin.R
  R/iNZDataModWin.R
  scripts/datetimes.R
  scripts/joindata.R
  scripts/reshaping.R
Labels: enhancement

#171 Bugfix/import rds factor
  NEWS.Md
  R/iNZLoadSave.R
  R/iNZMenuBarWidget.R
  tests/testthat/test_data_loads.R
  tests/testthat/test_rds.R
Labels: bug

#178 Merge dev bugfixes
  R/iNZChangeDataWin.R
  R/iNZDataModWin.R
  scripts/Join2.csv
  scripts/Join3.csv
  scripts/datetimes.R
  scripts/joindata.R
  scripts/reshaping.R
Labels: bug
